// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckControlAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['AckControlAction'](arg1, arg2, arg3);
}

export function AcpListSessions(arg1, arg2) {
  return window['go']['main']['App']['AcpListSessions'](arg1, arg2);
}

export function AcpRespondPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcpRespondPermission'](arg1, arg2, arg3);
}

export function AcpRespondUserInput(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcpRespondUserInput'](arg1, arg2, arg3);
}

export function AcpSend(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcpSend'](arg1, arg2, arg3);
}

export function AcpSetConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcpSetConfig'](arg1, arg2, arg3);
}

export function AcpSetMode(arg1, arg2) {
  return window['go']['main']['App']['AcpSetMode'](arg1, arg2);
}

export function AcpStart(arg1) {
  return window['go']['main']['App']['AcpStart'](arg1);
}

export function AcpStop(arg1) {
  return window['go']['main']['App']['AcpStop'](arg1);
}

export function AddMcpServer(arg1, arg2) {
  return window['go']['main']['App']['AddMcpServer'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CheckpointDiff(arg1, arg2) {
  return window['go']['main']['App']['CheckpointDiff'](arg1, arg2);
}

export function ClaudeAbort(arg1) {
  return window['go']['main']['App']['ClaudeAbort'](arg1);
}

export function ClaudeGetAccount(arg1) {
  return window['go']['main']['App']['ClaudeGetAccount'](arg1);
}

export function ClaudePlanUsage(arg1, arg2) {
  return window['go']['main']['App']['ClaudePlanUsage'](arg1, arg2);
}

export function ClaudeRespondControl(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClaudeRespondControl'](arg1, arg2, arg3);
}

export function ClaudeSend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ClaudeSend'](arg1, arg2, arg3, arg4);
}

export function ClaudeStart(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['ClaudeStart'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function ClaudeStop(arg1) {
  return window['go']['main']['App']['ClaudeStop'](arg1);
}

export function ClaudeUsage5h(arg1) {
  return window['go']['main']['App']['ClaudeUsage5h'](arg1);
}

export function CleanDaemon() {
  return window['go']['main']['App']['CleanDaemon']();
}

export function CodexListModels(arg1) {
  return window['go']['main']['App']['CodexListModels'](arg1);
}

export function CodexSend(arg1, arg2, arg3) {
  return window['go']['main']['App']['CodexSend'](arg1, arg2, arg3);
}

export function CodexStart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CodexStart'](arg1, arg2, arg3, arg4);
}

export function CodexStop(arg1) {
  return window['go']['main']['App']['CodexStop'](arg1);
}

export function ConfigFilePath() {
  return window['go']['main']['App']['ConfigFilePath']();
}

export function ControlVerbs() {
  return window['go']['main']['App']['ControlVerbs']();
}

export function CreateCheckpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCheckpoint'](arg1, arg2, arg3);
}

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function CreatePty(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePty'](arg1, arg2, arg3, arg4);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function CreateWorktree(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateWorktree'](arg1, arg2, arg3, arg4, arg5);
}

export function DaemonStats() {
  return window['go']['main']['App']['DaemonStats']();
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function FormatSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['FormatSource'](arg1, arg2, arg3);
}

export function GenerateCommitMessage(arg1) {
  return window['go']['main']['App']['GenerateCommitMessage'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetHookServerPort() {
  return window['go']['main']['App']['GetHookServerPort']();
}

export function GetHttpServerStatus() {
  return window['go']['main']['App']['GetHttpServerStatus']();
}

export function GetTailscaleStatus() {
  return window['go']['main']['App']['GetTailscaleStatus']();
}

export function HomeDir() {
  return window['go']['main']['App']['HomeDir']();
}

export function InstallUpdate(arg1, arg2) {
  return window['go']['main']['App']['InstallUpdate'](arg1, arg2);
}

export function IsPidAlive(arg1) {
  return window['go']['main']['App']['IsPidAlive'](arg1);
}

export function KeybindingsFilePath() {
  return window['go']['main']['App']['KeybindingsFilePath']();
}

export function KillOrphanSessions(arg1) {
  return window['go']['main']['App']['KillOrphanSessions'](arg1);
}

export function KillPty(arg1) {
  return window['go']['main']['App']['KillPty'](arg1);
}

export function ListCheckpoints(arg1, arg2) {
  return window['go']['main']['App']['ListCheckpoints'](arg1, arg2);
}

export function ListClaudeSessions(arg1) {
  return window['go']['main']['App']['ListClaudeSessions'](arg1);
}

export function ListFonts() {
  return window['go']['main']['App']['ListFonts']();
}

export function ListMcpServers() {
  return window['go']['main']['App']['ListMcpServers']();
}

export function ListOpenTargets() {
  return window['go']['main']['App']['ListOpenTargets']();
}

export function ListPtySessions() {
  return window['go']['main']['App']['ListPtySessions']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListTerminalTabs(arg1) {
  return window['go']['main']['App']['ListTerminalTabs'](arg1);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LspSend(arg1, arg2) {
  return window['go']['main']['App']['LspSend'](arg1, arg2);
}

export function LspStart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LspStart'](arg1, arg2, arg3, arg4);
}

export function LspStop(arg1) {
  return window['go']['main']['App']['LspStop'](arg1);
}

export function NotifyFloatGrid(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotifyFloatGrid'](arg1, arg2, arg3);
}

export function OpenGitPanelWindow() {
  return window['go']['main']['App']['OpenGitPanelWindow']();
}

export function OpenPathIn(arg1, arg2) {
  return window['go']['main']['App']['OpenPathIn'](arg1, arg2);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFile(arg1, arg2) {
  return window['go']['main']['App']['PickFile'](arg1, arg2);
}

export function PickFiles(arg1, arg2) {
  return window['go']['main']['App']['PickFiles'](arg1, arg2);
}

export function ProbeProvider(arg1, arg2) {
  return window['go']['main']['App']['ProbeProvider'](arg1, arg2);
}

export function ReadClaudeActivity(arg1, arg2) {
  return window['go']['main']['App']['ReadClaudeActivity'](arg1, arg2);
}

export function ReadClaudeTranscript(arg1, arg2) {
  return window['go']['main']['App']['ReadClaudeTranscript'](arg1, arg2);
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function ReadDirShallow(arg1) {
  return window['go']['main']['App']['ReadDirShallow'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReadKeybindings() {
  return window['go']['main']['App']['ReadKeybindings']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RegeneratePairCode() {
  return window['go']['main']['App']['RegeneratePairCode']();
}

export function RegisterTmuxWin(arg1, arg2) {
  return window['go']['main']['App']['RegisterTmuxWin'](arg1, arg2);
}

export function ReinstallStatusHooks() {
  return window['go']['main']['App']['ReinstallStatusHooks']();
}

export function RelaunchApp() {
  return window['go']['main']['App']['RelaunchApp']();
}

export function RemoteCreateChat(arg1) {
  return window['go']['main']['App']['RemoteCreateChat'](arg1);
}

export function RemoteListChats() {
  return window['go']['main']['App']['RemoteListChats']();
}

export function RemoteSyncChat(arg1) {
  return window['go']['main']['App']['RemoteSyncChat'](arg1);
}

export function RemoveMcpServer(arg1) {
  return window['go']['main']['App']['RemoveMcpServer'](arg1);
}

export function RemoveStatusHooks() {
  return window['go']['main']['App']['RemoveStatusHooks']();
}

export function RemoveWorktree(arg1, arg2) {
  return window['go']['main']['App']['RemoveWorktree'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function RepairAgentStatus() {
  return window['go']['main']['App']['RepairAgentStatus']();
}

export function RequestFloatSnapshot(arg1) {
  return window['go']['main']['App']['RequestFloatSnapshot'](arg1);
}

export function ResizePty(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePty'](arg1, arg2, arg3);
}

export function RestartDaemon() {
  return window['go']['main']['App']['RestartDaemon']();
}

export function RestoreCheckpoint(arg1, arg2) {
  return window['go']['main']['App']['RestoreCheckpoint'](arg1, arg2);
}

export function RunGh(arg1, arg2) {
  return window['go']['main']['App']['RunGh'](arg1, arg2);
}

export function RunGit(arg1, arg2) {
  return window['go']['main']['App']['RunGit'](arg1, arg2);
}

export function SaveTempImage(arg1, arg2) {
  return window['go']['main']['App']['SaveTempImage'](arg1, arg2);
}

export function SaveTerminalTabs(arg1, arg2) {
  return window['go']['main']['App']['SaveTerminalTabs'](arg1, arg2);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SendFloatSnapshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFloatSnapshot'](arg1, arg2, arg3, arg4);
}

export function SetBurrowMcpMaxDepth(arg1) {
  return window['go']['main']['App']['SetBurrowMcpMaxDepth'](arg1);
}

export function SetHttpEnabled(arg1) {
  return window['go']['main']['App']['SetHttpEnabled'](arg1);
}

export function SetMaxAgents(arg1) {
  return window['go']['main']['App']['SetMaxAgents'](arg1);
}

export function SetSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetSkillEnabled'](arg1, arg2);
}

export function SetSleepInhibit(arg1) {
  return window['go']['main']['App']['SetSleepInhibit'](arg1);
}

export function SetTabLiveStatus(arg1, arg2) {
  return window['go']['main']['App']['SetTabLiveStatus'](arg1, arg2);
}

export function SetTailscaleServe(arg1, arg2) {
  return window['go']['main']['App']['SetTailscaleServe'](arg1, arg2);
}

export function SetWorkspaceIcon(arg1, arg2) {
  return window['go']['main']['App']['SetWorkspaceIcon'](arg1, arg2);
}

export function SetWorkspaceOrder(arg1) {
  return window['go']['main']['App']['SetWorkspaceOrder'](arg1);
}

export function SystemStats() {
  return window['go']['main']['App']['SystemStats']();
}

export function TailscaleServe(arg1) {
  return window['go']['main']['App']['TailscaleServe'](arg1);
}

export function TailscaleServeStop() {
  return window['go']['main']['App']['TailscaleServeStop']();
}

export function TouchWorkspace(arg1) {
  return window['go']['main']['App']['TouchWorkspace'](arg1);
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}

export function WriteKeybindings(arg1) {
  return window['go']['main']['App']['WriteKeybindings'](arg1);
}

export function WritePty(arg1, arg2) {
  return window['go']['main']['App']['WritePty'](arg1, arg2);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
