// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AckControlAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AcpListSessions(arg1:string,arg2:string):Promise<number>;

export function AcpRespondPermission(arg1:string,arg2:number,arg3:string):Promise<void>;

export function AcpRespondUserInput(arg1:string,arg2:number,arg3:Record<string, Array<string>>):Promise<void>;

export function AcpSend(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function AcpSetConfig(arg1:string,arg2:string,arg3:string):Promise<number>;

export function AcpSetMode(arg1:string,arg2:string):Promise<number>;

export function AcpStart(arg1:main.AcpStartOpts):Promise<void>;

export function AcpStop(arg1:string):Promise<void>;

export function AddMcpServer(arg1:string,arg2:Record<string, any>):Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function CheckpointDiff(arg1:string,arg2:string):Promise<string>;

export function ClaudeAbort(arg1:string):Promise<void>;

export function ClaudeGetAccount(arg1:string):Promise<main.ClaudeAccountInfo>;

export function ClaudePlanUsage(arg1:string,arg2:boolean):Promise<main.ClaudeUsage>;

export function ClaudeRespondControl(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function ClaudeSend(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function ClaudeStart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<void>;

export function ClaudeStop(arg1:string):Promise<void>;

export function ClaudeUsage5h(arg1:string):Promise<main.ClaudeUsage>;

export function CleanDaemon():Promise<number>;

export function CodexListModels(arg1:string):Promise<Array<main.AgentModel>>;

export function CodexSend(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function CodexStart(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<void>;

export function CodexStop(arg1:string):Promise<void>;

export function ConfigFilePath():Promise<string>;

export function ControlVerbs():Promise<Array<main.ControlVerb>>;

export function CreateCheckpoint(arg1:string,arg2:string,arg3:string):Promise<main.Checkpoint>;

export function CreateDir(arg1:string):Promise<void>;

export function CreatePty(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<main.Workspace>;

export function CreateWorktree(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Workspace>;

export function DaemonStats():Promise<Record<string, any>>;

export function DeleteChatMessages(arg1:number):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:number):Promise<void>;

export function FormatSource(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateChatTitle(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateCommitMessage(arg1:string,arg2:string):Promise<main.GitOutput>;

export function GetAppVersion():Promise<string>;

export function GetHookServerPort():Promise<number>;

export function GetHttpServerStatus():Promise<main.HttpServerStatus>;

export function GetTailscaleStatus():Promise<main.TailscaleStatus>;

export function HomeDir():Promise<string>;

export function InstallUpdate(arg1:string,arg2:string):Promise<void>;

export function IsPidAlive(arg1:number):Promise<boolean>;

export function KeybindingsFilePath():Promise<string>;

export function KillOrphanSessions(arg1:Array<string>):Promise<number>;

export function KillPty(arg1:string):Promise<void>;

export function LatestNpmVersion(arg1:string):Promise<main.ProviderLatest>;

export function ListCheckpoints(arg1:string,arg2:number):Promise<Array<main.Checkpoint>>;

export function ListClaudeSessions(arg1:string):Promise<Array<main.ClaudeSessionInfo>>;

export function ListFonts():Promise<Array<string>>;

export function ListMcpServers():Promise<Record<string, any>>;

export function ListOpenTargets():Promise<Array<main.OpenTarget>>;

export function ListPtySessions():Promise<Array<string>>;

export function ListSkills():Promise<Array<main.SkillInfo>>;

export function ListTerminalTabs(arg1:number):Promise<Array<main.TerminalTab>>;

export function ListWorkspaces():Promise<Array<main.Workspace>>;

export function LoadChatMessages(arg1:number):Promise<string>;

export function LspSend(arg1:string,arg2:string):Promise<void>;

export function LspStart(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function LspStop(arg1:string):Promise<void>;

export function NotifyFloatGrid(arg1:string,arg2:number,arg3:number):Promise<void>;

export function OpenGitPanelWindow():Promise<void>;

export function OpenPathIn(arg1:string,arg2:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFile(arg1:string,arg2:Array<string>):Promise<string>;

export function PickFiles(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function ProbeProvider(arg1:string,arg2:string):Promise<main.ProviderProbe>;

export function ReadClaudeActivity(arg1:string,arg2:string):Promise<string>;

export function ReadClaudeTranscript(arg1:string,arg2:string):Promise<Array<string>>;

export function ReadConfig():Promise<string>;

export function ReadDirShallow(arg1:string):Promise<Array<main.DirEntry>>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadKeybindings():Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RegeneratePairCode():Promise<string>;

export function RegisterTmuxWin(arg1:string,arg2:string):Promise<void>;

export function ReinstallStatusHooks():Promise<void>;

export function RelaunchApp():Promise<void>;

export function RemoteCreateChat(arg1:string):Promise<Record<string, any>>;

export function RemoteListChats():Promise<Array<Record<string, any>>>;

export function RemoteSyncChat(arg1:Record<string, any>):Promise<void>;

export function RemoveMcpServer(arg1:string):Promise<void>;

export function RemoveStatusHooks():Promise<void>;

export function RemoveWorktree(arg1:number,arg2:boolean):Promise<void>;

export function RenameWorkspace(arg1:number,arg2:string):Promise<void>;

export function RepairAgentStatus():Promise<number>;

export function RequestFloatSnapshot(arg1:string):Promise<void>;

export function ResizePty(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartDaemon():Promise<void>;

export function RestoreCheckpoint(arg1:string,arg2:string):Promise<main.Checkpoint>;

export function RunGh(arg1:string,arg2:Array<string>):Promise<main.GitOutput>;

export function RunGit(arg1:string,arg2:Array<string>):Promise<main.GitOutput>;

export function SaveChatMessages(arg1:number,arg2:string):Promise<void>;

export function SaveTempImage(arg1:string,arg2:string):Promise<string>;

export function SaveTerminalTabs(arg1:number,arg2:Array<main.TerminalTab>):Promise<void>;

export function SearchFiles(arg1:string,arg2:string,arg3:number):Promise<Array<main.SearchHit>>;

export function SendFloatSnapshot(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SetBurrowMcpMaxDepth(arg1:number):Promise<void>;

export function SetHttpEnabled(arg1:boolean):Promise<void>;

export function SetMaxAgents(arg1:number):Promise<void>;

export function SetSkillEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetSleepInhibit(arg1:boolean):Promise<void>;

export function SetTabLiveStatus(arg1:string,arg2:string):Promise<void>;

export function SetTailscaleServe(arg1:boolean,arg2:number):Promise<main.TailscaleStatus>;

export function SetWorkspaceIcon(arg1:number,arg2:string):Promise<void>;

export function SetWorkspaceOrder(arg1:Array<number>):Promise<void>;

export function SystemStats():Promise<main.SystemStats>;

export function TailscaleServe(arg1:number):Promise<string>;

export function TailscaleServeStop():Promise<void>;

export function TouchWorkspace(arg1:number):Promise<void>;

export function WriteConfig(arg1:string):Promise<void>;

export function WriteKeybindings(arg1:string):Promise<void>;

export function WritePty(arg1:string,arg2:Array<number>):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
