<script setup lang="ts">
import { PhArrowLeft, PhBookOpen, PhGearSix, PhRobot } from "@phosphor-icons/vue";
defineEmits<{ close: []; onboarding: []; shortcuts: [] }>();
</script>

<template>
  <section class="docs-screen" aria-label="Burrow documentation">
    <header class="docs-header"><button type="button" @click="$emit('close')"><PhArrowLeft :size="16" /> Back</button><span><PhBookOpen :size="16" /> Documentation</span></header>
    <div class="docs-body"><aside><p>GETTING STARTED</p><button class="active">Welcome to Burrow</button><button @click="$emit('onboarding')">Run onboarding again</button><button @click="$emit('shortcuts')">Keyboard shortcuts</button><p>WORKSPACES</p><button>Projects and threads</button><button>Agents and terminals</button><p>SETTINGS</p><button><PhGearSix :size="14" /> Preferences</button></aside>
      <article><p class="docs-kicker">GETTING STARTED</p><h1>Welcome to Burrow</h1><p class="lead">Burrow is a native workspace for running and coordinating AI coding agents without losing track of the work around them.</p><h2>Start with a project</h2><p>Open a folder, then use the composer to begin a chat or start an agent in a terminal. Every project keeps its terminals, threads, and Git context together.</p><h2>Keep agent work visible</h2><p>Agent status is surfaced in the workspace, so you can keep coding while Burrow tells you when a result needs review or an agent is waiting.</p><div class="docs-callout"><PhRobot :size="18" /><span>Need a refresher? Re-run the onboarding from Help at any time.</span></div></article>
    </div>
  </section>
</template>

<style scoped>
.docs-screen { position: fixed; inset: 0; z-index: 1090; display: grid; grid-template-rows: 52px 1fr; background: var(--bg-base); color: var(--text-primary); }.docs-header { display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid var(--border); background: var(--bg-panel); padding: 0 24px; font-size: 13px; font-weight: 600; }.docs-header span, .docs-header button { display: inline-flex; align-items: center; gap: 8px; }.docs-header button { border: 0; background: transparent; color: var(--text-secondary); cursor: pointer; font: inherit; }.docs-header button:hover { color: var(--text-primary); }.docs-body { display: grid; grid-template-columns: 238px minmax(0, 1fr); overflow: hidden; }.docs-body aside { display: flex; flex-direction: column; gap: 2px; overflow-y: auto; border-right: 1px solid var(--border); background: var(--bg-panel); padding: 24px 12px; }.docs-body aside p { margin: 18px 8px 5px; color: var(--text-muted); font-size: 10px; font-weight: 700; letter-spacing: .08em; }.docs-body aside p:first-child { margin-top: 0; }.docs-body aside button { display: flex; align-items: center; gap: 7px; border: 0; border-radius: 5px; background: transparent; color: var(--text-secondary); cursor: pointer; padding: 7px 8px; font: inherit; font-size: 12px; text-align: left; }.docs-body aside button:hover, .docs-body aside button.active { background: var(--bg-hover); color: var(--text-primary); }.docs-body article { width: min(720px, calc(100% - 64px)); overflow-y: auto; margin: 0 auto; padding: 66px 0 100px; }.docs-kicker { margin: 0 0 12px; color: var(--accent); font-size: 11px; font-weight: 700; letter-spacing: .08em; }.docs-body h1 { margin: 0; font-size: 34px; letter-spacing: -.04em; }.docs-body .lead { max-width: 62ch; margin: 16px 0 42px; color: var(--text-secondary); font-size: 16px; line-height: 1.65; }.docs-body h2 { margin: 34px 0 8px; font-size: 17px; }.docs-body article > p:not(.docs-kicker):not(.lead) { max-width: 65ch; margin: 0; color: var(--text-secondary); font-size: 14px; line-height: 1.65; }.docs-callout { display: flex; align-items: center; gap: 11px; margin-top: 34px; border: 1px solid var(--border); border-radius: 7px; background: var(--bg-panel); color: var(--text-secondary); padding: 14px; font-size: 12px; }.docs-callout svg { color: var(--accent); flex: 0 0 auto; }
</style>
