import type { ITheme } from "@xterm/xterm";

// A Theme restyles the whole app: chrome (CSS vars), the terminal (xterm
// palette) and the diff viewer (shiki/@pierre theme name) together. The CSS var
// keys mirror the color set authored in App.vue's `:root` (font + layout vars
// are intentionally NOT part of a theme).
export interface Theme {
  key: string;
  label: string;
  isDark: boolean;
  // CSS custom-property values, keyed WITHOUT the leading `--`.
  vars: {
    "bg-base": string;
    "bg-panel": string;
    "bg-hover": string;
    "bg-selected": string;
    border: string;
    "text-primary": string;
    "text-secondary": string;
    "text-muted": string;
    accent: string;
    "accent-dim": string;
    green: string;
    yellow: string;
    red: string;
  };
  xterm: ITheme;
  // A @pierre/diffs theme name (accepts any shiki BundledTheme).
  shiki: string;
  // Optional full-window background. A CSS `background` value (url(), gradient,
  // etc.) painted on <body> behind the chrome. Panels with rgba()/transparent
  // bg vars let it peek through. Used by joke/meme themes; omit for normal ones.
  bgImage?: string;
  // Optional CSS `backdrop-filter` value (e.g. "blur(24px)") applied to the
  // app's translucent surfaces. Pairs with rgba bg vars + OS window vibrancy to
  // make a see-through, frosted window. Omit → "none".
  backdropBlur?: string;
}

// Inline meme wallpaper for the "Stonks" theme: tiled neon emoji + ALL-CAPS
// hype text on a deep purple void, baked as a data-URI SVG so it ships offline
// (no network fetch in the desktop app). Crazy on purpose.
const STONKS_BG =
  "url(\"data:image/svg+xml," +
  encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' width='340' height='240'>
      <defs>
        <linearGradient id='g' x1='0' y1='0' x2='1' y2='1'>
          <stop offset='0' stop-color='#16001f'/>
          <stop offset='1' stop-color='#04000a'/>
        </linearGradient>
      </defs>
      <rect width='340' height='240' fill='url(#g)'/>
      <text x='14' y='52' font-size='40' opacity='0.10'>🚀</text>
      <text x='250' y='44' font-size='40' opacity='0.10'>💎</text>
      <text x='150' y='150' font-size='44' opacity='0.10'>🐕</text>
      <text x='40' y='200' font-size='40' opacity='0.10'>🔥</text>
      <text x='270' y='210' font-size='40' opacity='0.10'>💸</text>
      <text x='80' y='110' font-family='Impact, sans-serif' font-size='26' fill='#39ff14' opacity='0.12' transform='rotate(-12 80 110)'>STONKS</text>
      <text x='180' y='90' font-family='Impact, sans-serif' font-size='20' fill='#ff2079' opacity='0.12' transform='rotate(8 180 90)'>MUCH WOW</text>
      <text x='30' y='230' font-family='Impact, sans-serif' font-size='18' fill='#00f0ff' opacity='0.12'>TO THE MOON</text>
    </svg>`,
  ) +
  "\")";

export const THEMES: Theme[] = [
  {
    key: "dark",
    label: "Dark",
    isDark: true,
    vars: {
      "bg-base": "#0e0c14",
      "bg-panel": "#16131f",
      "bg-hover": "#201c2d",
      "bg-selected": "#2a2138",
      border: "#262233",
      "text-primary": "#f0eef7",
      "text-secondary": "#a9a2c0",
      "text-muted": "#6f6885",
      accent: "#ec4899",
      "accent-dim": "#be185d",
      green: "#34d399",
      yellow: "#fbbf24",
      red: "#f87171",
    },
    xterm: {
      background: "#0a0810",
      foreground: "#f0eef7",
      cursor: "#ec4899",
      cursorAccent: "#0a0810",
      selectionBackground: "#2a2138",
      black: "#1e1b29",
      red: "#f87171",
      green: "#34d399",
      yellow: "#fbbf24",
      blue: "#818cf8",
      magenta: "#ec4899",
      cyan: "#22d3ee",
      white: "#c7c2d9",
      brightBlack: "#6f6885",
      brightRed: "#fca5a5",
      brightGreen: "#6ee7b7",
      brightYellow: "#fcd34d",
      brightBlue: "#a5b4fc",
      brightMagenta: "#f472b6",
      brightCyan: "#67e8f9",
      brightWhite: "#f0eef7",
    },
    shiki: "github-dark",
  },
  {
    key: "light",
    label: "Light",
    isDark: false,
    vars: {
      "bg-base": "#ffffff",
      "bg-panel": "#f5f5f5",
      "bg-hover": "#e8e8ec",
      "bg-selected": "#cfe3ff",
      border: "#c2c2cc",
      "text-primary": "#0f172a",
      "text-secondary": "#3a4759",
      "text-muted": "#64748b",
      accent: "#2563eb",
      "accent-dim": "#1d4ed8",
      green: "#16a34a",
      yellow: "#ca8a04",
      red: "#dc2626",
    },
    xterm: {
      background: "#ffffff",
      foreground: "#1e293b",
      cursor: "#2563eb",
      cursorAccent: "#ffffff",
      selectionBackground: "#cfe3ff",
      black: "#1e293b",
      red: "#dc2626",
      green: "#16a34a",
      yellow: "#ca8a04",
      blue: "#2563eb",
      magenta: "#9333ea",
      cyan: "#0891b2",
      white: "#64748b",
      brightBlack: "#475569",
      brightRed: "#ef4444",
      brightGreen: "#22c55e",
      brightYellow: "#eab308",
      brightBlue: "#3b82f6",
      brightMagenta: "#a855f7",
      brightCyan: "#06b6d4",
      brightWhite: "#1e293b",
    },
    shiki: "github-light",
  },
  {
    key: "monokai",
    label: "Monokai",
    isDark: true,
    vars: {
      "bg-base": "#1e1f1c",
      "bg-panel": "#272822",
      "bg-hover": "#3e3d32",
      "bg-selected": "#49483e",
      border: "#4d4b3e",
      "text-primary": "#f8f8f2",
      "text-secondary": "#d3d2c6",
      "text-muted": "#9d9883",
      accent: "#fd971f",
      "accent-dim": "#cc7a16",
      green: "#a6e22e",
      yellow: "#e6db74",
      red: "#f92672",
    },
    xterm: {
      background: "#272822",
      foreground: "#f8f8f2",
      cursor: "#fd971f",
      cursorAccent: "#272822",
      selectionBackground: "#49483e",
      black: "#272822",
      red: "#f92672",
      green: "#a6e22e",
      yellow: "#f4bf75",
      blue: "#66d9ef",
      magenta: "#ae81ff",
      cyan: "#a1efe4",
      white: "#f8f8f2",
      brightBlack: "#75715e",
      brightRed: "#f92672",
      brightGreen: "#a6e22e",
      brightYellow: "#e6db74",
      brightBlue: "#66d9ef",
      brightMagenta: "#ae81ff",
      brightCyan: "#a1efe4",
      brightWhite: "#f9f8f5",
    },
    shiki: "monokai",
  },
  {
    key: "cobalt2",
    label: "Cobalt2",
    isDark: true,
    vars: {
      "bg-base": "#193549",
      "bg-panel": "#15232d",
      "bg-hover": "#1f4662",
      "bg-selected": "#0d3a58",
      border: "#2d6088",
      "text-primary": "#ffffff",
      "text-secondary": "#bcd3e0",
      "text-muted": "#8aa6bb",
      accent: "#ffc600",
      "accent-dim": "#cc9e00",
      green: "#3ad900",
      yellow: "#ffc600",
      red: "#ff628c",
    },
    xterm: {
      background: "#193549",
      foreground: "#ffffff",
      cursor: "#ffc600",
      cursorAccent: "#193549",
      selectionBackground: "#0d3a58",
      black: "#000000",
      red: "#ff628c",
      green: "#3ad900",
      yellow: "#ffc600",
      blue: "#0088ff",
      magenta: "#ff9d00",
      cyan: "#80fcff",
      white: "#ffffff",
      brightBlack: "#6e8ba0",
      brightRed: "#ff628c",
      brightGreen: "#3ad900",
      brightYellow: "#ffc600",
      brightBlue: "#0088ff",
      brightMagenta: "#ff9d00",
      brightCyan: "#80fcff",
      brightWhite: "#ffffff",
    },
    shiki: "github-dark",
  },
  {
    key: "solarized-light",
    label: "Solarized Light",
    isDark: false,
    vars: {
      "bg-base": "#fdf6e3",
      "bg-panel": "#eee8d5",
      "bg-hover": "#e4ddc8",
      "bg-selected": "#d7e7e9",
      border: "#c7bd9f",
      "text-primary": "#073642",
      "text-secondary": "#3f5358",
      "text-muted": "#7c8a8a",
      accent: "#268bd2",
      "accent-dim": "#1f6f9f",
      green: "#859900",
      yellow: "#b58900",
      red: "#dc322f",
    },
    xterm: {
      background: "#fdf6e3",
      foreground: "#586e75",
      cursor: "#268bd2",
      cursorAccent: "#fdf6e3",
      selectionBackground: "#d7e7e9",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#586e75",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
    shiki: "solarized-light",
  },
  {
    key: "dracula",
    label: "Dracula",
    isDark: true,
    vars: {
      "bg-base": "#282a36",
      "bg-panel": "#21222c",
      "bg-hover": "#343746",
      "bg-selected": "#44475a",
      border: "#4a4d63",
      "text-primary": "#f8f8f2",
      "text-secondary": "#d2d4e0",
      "text-muted": "#8b94bb",
      accent: "#bd93f9",
      "accent-dim": "#9a73d4",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      red: "#ff5555",
    },
    xterm: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#bd93f9",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
    shiki: "dracula",
  },
  // ── ported from crynta/terax-ai ──────────────────────────────────────────
  {
    key: "tokyo-night",
    label: "Tokyo Night",
    isDark: true,
    vars: {
      "bg-base": "#1a1b26",
      "bg-panel": "#1f2030",
      "bg-hover": "#292e42",
      "bg-selected": "#2a2d4a",
      border: "rgba(255,255,255,0.08)",
      "text-primary": "#c0caf5",
      "text-secondary": "#9aa5ce",
      "text-muted": "#6b7599",
      accent: "#7aa2f7",
      "accent-dim": "#5271c4",
      green: "#9ece6a",
      yellow: "#e0af68",
      red: "#f7768e",
    },
    xterm: {
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      cursorAccent: "#1a1b26",
      selectionBackground: "rgba(122,162,247,0.25)",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#ff7a93",
      brightGreen: "#b9f27c",
      brightYellow: "#ff9e64",
      brightBlue: "#7da6ff",
      brightMagenta: "#bb9af7",
      brightCyan: "#0db9d7",
      brightWhite: "#c0caf5",
    },
    shiki: "tokyo-night",
  },
  {
    key: "caffeine",
    label: "Caffeine",
    isDark: true,
    vars: {
      "bg-base": "#111111",
      "bg-panel": "#191919",
      "bg-hover": "#2a2a2a",
      "bg-selected": "#393028",
      border: "#201e18",
      "text-primary": "#eeeeee",
      "text-secondary": "#c4c4c4",
      "text-muted": "#b4b4b4",
      accent: "#ffe0c2",
      "accent-dim": "#cc9e80",
      green: "#b5c98f",
      yellow: "#ffd9a0",
      red: "#e06c75",
    },
    xterm: {
      background: "#111111",
      foreground: "#eeeeee",
      cursor: "#ffe0c2",
      cursorAccent: "#111111",
      selectionBackground: "rgba(255,224,194,0.20)",
      black: "#393028",
      red: "#e06c75",
      green: "#b5c98f",
      yellow: "#ffd9a0",
      blue: "#8fb0d9",
      magenta: "#cba6c9",
      cyan: "#88c0c8",
      white: "#d8cbb8",
      brightBlack: "#5c5046",
      brightRed: "#ff8a93",
      brightGreen: "#c9dba8",
      brightYellow: "#ffe6c4",
      brightBlue: "#a9c3e0",
      brightMagenta: "#ddc0db",
      brightCyan: "#a4d4da",
      brightWhite: "#f0e6d6",
    },
    shiki: "github-dark",
  },
  {
    key: "tide",
    label: "Tide",
    isDark: true,
    vars: {
      "bg-base": "#14191c",
      "bg-panel": "#1a2024",
      "bg-hover": "#232c30",
      "bg-selected": "#283330",
      border: "rgba(205,217,218,0.09)",
      "text-primary": "#cdd9da",
      "text-secondary": "#a8b8ba",
      "text-muted": "#93a3a4",
      accent: "#6cb6b0",
      "accent-dim": "#4a8f8a",
      green: "#8fc99a",
      yellow: "#d9bd80",
      red: "#e07a6a",
    },
    xterm: {
      background: "#14191c",
      foreground: "#cdd9da",
      cursor: "#6cb6b0",
      cursorAccent: "#14191c",
      selectionBackground: "rgba(108,182,176,0.20)",
      black: "#283330",
      red: "#e07a6a",
      green: "#8fc99a",
      yellow: "#d9bd80",
      blue: "#6fa8c9",
      magenta: "#c39bc4",
      cyan: "#6cb6b0",
      white: "#cdd9da",
      brightBlack: "#44504d",
      brightRed: "#ec8a7a",
      brightGreen: "#a0d6aa",
      brightYellow: "#e3c896",
      brightBlue: "#82bbd9",
      brightMagenta: "#d0aed0",
      brightCyan: "#82c8c2",
      brightWhite: "#e0eaeb",
    },
    shiki: "nord",
  },
  {
    key: "tide-light",
    label: "Tide Light",
    isDark: false,
    vars: {
      "bg-base": "#f2f6f5",
      "bg-panel": "#ffffff",
      "bg-hover": "#e3ecea",
      "bg-selected": "#dde7e4",
      border: "rgba(43,58,57,0.12)",
      "text-primary": "#2b3a39",
      "text-secondary": "#3d5352",
      "text-muted": "#5f6e6d",
      accent: "#2f7d76",
      "accent-dim": "#1f5f58",
      green: "#3a8a4f",
      yellow: "#a9802a",
      red: "#c0392b",
    },
    xterm: {
      background: "#f2f6f5",
      foreground: "#2b3a39",
      cursor: "#2f7d76",
      cursorAccent: "#f2f6f5",
      selectionBackground: "rgba(47,125,118,0.16)",
      black: "#2b3a39",
      red: "#c0392b",
      green: "#3a8a4f",
      yellow: "#a9802a",
      blue: "#3a6ea5",
      magenta: "#9a5a8a",
      cyan: "#2f7d76",
      white: "#c2c8c7",
      brightBlack: "#5a6968",
      brightRed: "#d04a3a",
      brightGreen: "#469a5f",
      brightYellow: "#b8902a",
      brightBlue: "#4a7eb5",
      brightMagenta: "#aa6a9a",
      brightCyan: "#3a958c",
      brightWhite: "#2b3a39",
    },
    shiki: "github-light",
  },
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: "stonks",
    label: "Stonks 🚀 (meme)",
    isDark: true,
    // Panel bgs are rgba with alpha so the meme wallpaper bleeds through every
    // surface. Accents are eye-melting neon — magenta/cyan/acid-green.
    vars: {
      "bg-base": "#0a0012",
      "bg-panel": "rgba(22, 0, 38, 0.62)",
      "bg-hover": "rgba(255, 32, 121, 0.18)",
      "bg-selected": "rgba(0, 240, 255, 0.22)",
      border: "#ff2079",
      "text-primary": "#f5e9ff",
      "text-secondary": "#c9a8ff",
      "text-muted": "#8a6bb0",
      accent: "#39ff14",
      "accent-dim": "#00f0ff",
      green: "#39ff14",
      yellow: "#ffe600",
      red: "#ff2079",
    },
    xterm: {
      // Transparent so the meme wallpaper shows under the terminal text.
      background: "rgba(10, 0, 18, 0.45)",
      foreground: "#f5e9ff",
      cursor: "#39ff14",
      cursorAccent: "#0a0012",
      selectionBackground: "#3a006a",
      black: "#1a0030",
      red: "#ff2079",
      green: "#39ff14",
      yellow: "#ffe600",
      blue: "#00f0ff",
      magenta: "#d400ff",
      cyan: "#00f0ff",
      white: "#f5e9ff",
      brightBlack: "#6b4a8f",
      brightRed: "#ff5c9d",
      brightGreen: "#7dff5c",
      brightYellow: "#fff04d",
      brightBlue: "#5cf0ff",
      brightMagenta: "#e85cff",
      brightCyan: "#5cf0ff",
      brightWhite: "#ffffff",
    },
    shiki: "synthwave-84",
    bgImage: STONKS_BG,
  },
  {
    key: "lime-void",
    label: "Lime Void 🟢",
    isDark: true,
    // Solid dark-lime theme. (A see-through "glass" variant relying on window
    // transparency + OS vibrancy was tried but caused system instability and
    // left surfaces unreadable, so it's fully opaque. Electric lime accent.)
    vars: {
      "bg-base": "#060a06",
      "bg-panel": "#0c140c",
      "bg-hover": "rgba(174, 255, 0, 0.14)",
      "bg-selected": "rgba(174, 255, 0, 0.22)",
      border: "rgba(174, 255, 0, 0.35)",
      "text-primary": "#eaffd6",
      "text-secondary": "#b6e89a",
      "text-muted": "#7fa86a",
      accent: "#aeff00",
      "accent-dim": "#7ab800",
      green: "#aeff00",
      yellow: "#eaff00",
      red: "#ff5470",
    },
    xterm: {
      background: "#060a06",
      foreground: "#eaffd6",
      cursor: "#aeff00",
      cursorAccent: "#060a06",
      selectionBackground: "rgba(174, 255, 0, 0.25)",
      black: "#0a0f0a",
      red: "#ff5470",
      green: "#aeff00",
      yellow: "#eaff00",
      blue: "#5cf0c8",
      magenta: "#c8ff5c",
      cyan: "#7affd6",
      white: "#eaffd6",
      brightBlack: "#5a6b4a",
      brightRed: "#ff7a90",
      brightGreen: "#c6ff4d",
      brightYellow: "#f4ff4d",
      brightBlue: "#7affd6",
      brightMagenta: "#d6ff7a",
      brightCyan: "#a6ffe6",
      brightWhite: "#ffffff",
    },
    shiki: "github-dark",
  },
  {
    key: "nebula",
    label: "Nebula",
    isDark: true,
    vars: {
      "bg-base": "#0d0e1f",
      "bg-panel": "#13152b",
      "bg-hover": "#1e2040",
      "bg-selected": "#2d2060",
      border: "#252745",
      "text-primary": "#e4e7f5",
      "text-secondary": "#8d96c0",
      "text-muted": "#5a6390",
      accent: "#7c5af5",
      "accent-dim": "#5a3dd0",
      green: "#22c55e",
      yellow: "#f59e0b",
      red: "#f0506e",
    },
    xterm: {
      background: "#0b0c1e",
      foreground: "#c0caf5",
      cursor: "#7c5af5",
      cursorAccent: "#0b0c1e",
      selectionBackground: "#2d2060",
      black: "#15162c",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
    shiki: "github-dark",
  },
];

export const DEFAULT_THEME_KEY = "dark";

export function findTheme(key: string): Theme {
  return THEMES.find((t) => t.key === key) ?? THEMES[0];
}
