import type { ITheme } from "@xterm/xterm";

// A Theme restyles the whole app: chrome (CSS vars), the terminal (xterm
// palette) and the diff viewer (shiki/@pierre theme name) together. The CSS var
// keys mirror the color set authored in App.vue's `:root` (font + layout vars
// are intentionally NOT part of a theme).
export interface Theme {
  key: string;
  label: string;
  isDark: boolean;
  // CSS custom-property values, keyed WITHOUT the leading `--`.
  vars: {
    "bg-base": string;
    "bg-panel": string;
    "bg-hover": string;
    "bg-selected": string;
    border: string;
    "text-primary": string;
    "text-secondary": string;
    "text-muted": string;
    accent: string;
    "accent-dim": string;
    green: string;
    yellow: string;
    red: string;
  };
  xterm: ITheme;
  // A @pierre/diffs theme name (accepts any shiki BundledTheme).
  shiki: string;
  // Optional full-window background. A CSS `background` value (url(), gradient,
  // etc.) painted on <body> behind the chrome. Panels with rgba()/transparent
  // bg vars let it peek through. Used by joke/meme themes; omit for normal ones.
  bgImage?: string;
  // Optional CSS `backdrop-filter` value (e.g. "blur(24px)") applied to the
  // app's translucent surfaces. Pairs with rgba bg vars + OS window vibrancy to
  // make a see-through, frosted window. Omit → "none".
  backdropBlur?: string;
}

// Inline meme wallpaper for the "Stonks" theme: tiled neon emoji + ALL-CAPS
// hype text on a deep purple void, baked as a data-URI SVG so it ships offline
// (no network fetch in the desktop app). Crazy on purpose.
const STONKS_BG =
  "url(\"data:image/svg+xml," +
  encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' width='340' height='240'>
      <defs>
        <linearGradient id='g' x1='0' y1='0' x2='1' y2='1'>
          <stop offset='0' stop-color='#16001f'/>
          <stop offset='1' stop-color='#04000a'/>
        </linearGradient>
      </defs>
      <rect width='340' height='240' fill='url(#g)'/>
      <text x='14' y='52' font-size='40' opacity='0.10'>🚀</text>
      <text x='250' y='44' font-size='40' opacity='0.10'>💎</text>
      <text x='150' y='150' font-size='44' opacity='0.10'>🐕</text>
      <text x='40' y='200' font-size='40' opacity='0.10'>🔥</text>
      <text x='270' y='210' font-size='40' opacity='0.10'>💸</text>
      <text x='80' y='110' font-family='Impact, sans-serif' font-size='26' fill='#39ff14' opacity='0.12' transform='rotate(-12 80 110)'>STONKS</text>
      <text x='180' y='90' font-family='Impact, sans-serif' font-size='20' fill='#ff2079' opacity='0.12' transform='rotate(8 180 90)'>MUCH WOW</text>
      <text x='30' y='230' font-family='Impact, sans-serif' font-size='18' fill='#00f0ff' opacity='0.12'>TO THE MOON</text>
    </svg>`,
  ) +
  "\")";


// Daylight edition of the Stonks wallpaper, for its light variant: same tiled
// emoji + hype text, dark ink on a pale pink sky.
const STONKS_LIGHT_BG =
  "url(\"data:image/svg+xml," +
  encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' width='340' height='240'>
      <defs>
        <linearGradient id='gl' x1='0' y1='0' x2='1' y2='1'>
          <stop offset='0' stop-color='#fff2f9'/>
          <stop offset='1' stop-color='#ffe6f4'/>
        </linearGradient>
      </defs>
      <rect width='340' height='240' fill='url(#gl)'/>
      <text x='14' y='52' font-size='40' opacity='0.16'>🚀</text>
      <text x='250' y='44' font-size='40' opacity='0.16'>💎</text>
      <text x='150' y='150' font-size='44' opacity='0.16'>🐕</text>
      <text x='40' y='200' font-size='40' opacity='0.16'>🔥</text>
      <text x='270' y='210' font-size='40' opacity='0.16'>💸</text>
      <text x='80' y='110' font-family='Impact, sans-serif' font-size='26' fill='#0f8f2a' opacity='0.16' transform='rotate(-12 80 110)'>STONKS</text>
      <text x='180' y='90' font-family='Impact, sans-serif' font-size='20' fill='#d1006b' opacity='0.16' transform='rotate(8 180 90)'>MUCH WOW</text>
      <text x='30' y='230' font-family='Impact, sans-serif' font-size='18' fill='#0090a8' opacity='0.16'>TO THE MOON</text>
    </svg>`,
  ) +
  "\")";

export const THEMES: Theme[] = [
  {
    key: "dark",
    label: "Dark",
    isDark: true,
    vars: {
      "bg-base": "#0e0c14",
      "bg-panel": "#16131f",
      "bg-hover": "#201c2d",
      "bg-selected": "#2a2138",
      border: "#262233",
      "text-primary": "#f0eef7",
      "text-secondary": "#a9a2c0",
      "text-muted": "#6f6885",
      accent: "#ec4899",
      "accent-dim": "#be185d",
      green: "#34d399",
      yellow: "#fbbf24",
      red: "#f87171",
    },
    xterm: {
      background: "#0a0810",
      foreground: "#f0eef7",
      cursor: "#ec4899",
      cursorAccent: "#0a0810",
      selectionBackground: "#2a2138",
      black: "#1e1b29",
      red: "#f87171",
      green: "#34d399",
      yellow: "#fbbf24",
      blue: "#818cf8",
      magenta: "#ec4899",
      cyan: "#22d3ee",
      white: "#c7c2d9",
      brightBlack: "#6f6885",
      brightRed: "#fca5a5",
      brightGreen: "#6ee7b7",
      brightYellow: "#fcd34d",
      brightBlue: "#a5b4fc",
      brightMagenta: "#f472b6",
      brightCyan: "#67e8f9",
      brightWhite: "#f0eef7",
    },
    shiki: "github-dark",
  },
  {
    key: "light",
    label: "Light",
    isDark: false,
    vars: {
      "bg-base": "#ffffff",
      "bg-panel": "#f5f5f5",
      "bg-hover": "#e8e8ec",
      "bg-selected": "#cfe3ff",
      border: "#c2c2cc",
      "text-primary": "#0f172a",
      "text-secondary": "#3a4759",
      "text-muted": "#64748b",
      accent: "#2563eb",
      "accent-dim": "#1d4ed8",
      green: "#16a34a",
      yellow: "#ca8a04",
      red: "#dc2626",
    },
    xterm: {
      background: "#ffffff",
      foreground: "#1e293b",
      cursor: "#2563eb",
      cursorAccent: "#ffffff",
      selectionBackground: "#cfe3ff",
      black: "#1e293b",
      red: "#dc2626",
      green: "#16a34a",
      yellow: "#ca8a04",
      blue: "#2563eb",
      magenta: "#9333ea",
      cyan: "#0891b2",
      white: "#64748b",
      brightBlack: "#475569",
      brightRed: "#ef4444",
      brightGreen: "#22c55e",
      brightYellow: "#eab308",
      brightBlue: "#3b82f6",
      brightMagenta: "#a855f7",
      brightCyan: "#06b6d4",
      brightWhite: "#1e293b",
    },
    shiki: "github-light",
  },
  {
    key: "ps-gray",
    label: "Photoshop Gray",
    isDark: false,
    // Photoshop CS4-style neutral gray chrome: gray panels on a slightly
    // darker gray canvas, charcoal text, classic Adobe selection blue.
    vars: {
      "bg-base": "#bebebe",
      "bg-panel": "#d6d6d6",
      "bg-hover": "#c8c8c8",
      "bg-selected": "#b8cce4",
      border: "#9a9a9a",
      "text-primary": "#1e1e1e",
      "text-secondary": "#3c3c3c",
      "text-muted": "#6e6e6e",
      accent: "#3875d7",
      "accent-dim": "#2b5cab",
      green: "#2e7d32",
      yellow: "#a07800",
      red: "#c62828",
    },
    xterm: {
      background: "#e2e2e2",
      foreground: "#1e1e1e",
      cursor: "#3875d7",
      cursorAccent: "#e2e2e2",
      selectionBackground: "#b8cce4",
      black: "#1e1e1e",
      red: "#c62828",
      green: "#2e7d32",
      yellow: "#a07800",
      blue: "#3875d7",
      magenta: "#8e44ad",
      cyan: "#00838f",
      white: "#8c8c8c",
      brightBlack: "#5a5a5a",
      brightRed: "#e53935",
      brightGreen: "#43a047",
      brightYellow: "#c09000",
      brightBlue: "#5b8fe0",
      brightMagenta: "#a45cc4",
      brightCyan: "#00acc1",
      brightWhite: "#1e1e1e",
    },
    shiki: "github-light",
  },
  {
    key: "monokai",
    label: "Monokai",
    isDark: true,
    vars: {
      "bg-base": "#1e1f1c",
      "bg-panel": "#272822",
      "bg-hover": "#3e3d32",
      "bg-selected": "#49483e",
      border: "#4d4b3e",
      "text-primary": "#f8f8f2",
      "text-secondary": "#d3d2c6",
      "text-muted": "#9d9883",
      accent: "#fd971f",
      "accent-dim": "#cc7a16",
      green: "#a6e22e",
      yellow: "#e6db74",
      red: "#f92672",
    },
    xterm: {
      background: "#272822",
      foreground: "#f8f8f2",
      cursor: "#fd971f",
      cursorAccent: "#272822",
      selectionBackground: "#49483e",
      black: "#272822",
      red: "#f92672",
      green: "#a6e22e",
      yellow: "#f4bf75",
      blue: "#66d9ef",
      magenta: "#ae81ff",
      cyan: "#a1efe4",
      white: "#f8f8f2",
      brightBlack: "#75715e",
      brightRed: "#f92672",
      brightGreen: "#a6e22e",
      brightYellow: "#e6db74",
      brightBlue: "#66d9ef",
      brightMagenta: "#ae81ff",
      brightCyan: "#a1efe4",
      brightWhite: "#f9f8f5",
    },
    shiki: "monokai",
  },
  {
    key: "cobalt2",
    label: "Cobalt2",
    isDark: true,
    vars: {
      "bg-base": "#193549",
      "bg-panel": "#15232d",
      "bg-hover": "#1f4662",
      "bg-selected": "#0d3a58",
      border: "#2d6088",
      "text-primary": "#ffffff",
      "text-secondary": "#bcd3e0",
      "text-muted": "#8aa6bb",
      accent: "#ffc600",
      "accent-dim": "#cc9e00",
      green: "#3ad900",
      yellow: "#ffc600",
      red: "#ff628c",
    },
    xterm: {
      background: "#193549",
      foreground: "#ffffff",
      cursor: "#ffc600",
      cursorAccent: "#193549",
      selectionBackground: "#0d3a58",
      black: "#000000",
      red: "#ff628c",
      green: "#3ad900",
      yellow: "#ffc600",
      blue: "#0088ff",
      magenta: "#ff9d00",
      cyan: "#80fcff",
      white: "#ffffff",
      brightBlack: "#6e8ba0",
      brightRed: "#ff628c",
      brightGreen: "#3ad900",
      brightYellow: "#ffc600",
      brightBlue: "#0088ff",
      brightMagenta: "#ff9d00",
      brightCyan: "#80fcff",
      brightWhite: "#ffffff",
    },
    shiki: "github-dark",
  },
  {
    key: "solarized-light",
    label: "Solarized Light",
    isDark: false,
    vars: {
      "bg-base": "#fdf6e3",
      "bg-panel": "#eee8d5",
      "bg-hover": "#e4ddc8",
      "bg-selected": "#d7e7e9",
      border: "#c7bd9f",
      "text-primary": "#073642",
      "text-secondary": "#3f5358",
      "text-muted": "#7c8a8a",
      accent: "#268bd2",
      "accent-dim": "#1f6f9f",
      green: "#859900",
      yellow: "#b58900",
      red: "#dc322f",
    },
    xterm: {
      background: "#fdf6e3",
      foreground: "#586e75",
      cursor: "#268bd2",
      cursorAccent: "#fdf6e3",
      selectionBackground: "#d7e7e9",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#586e75",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
    shiki: "solarized-light",
  },
  {
    key: "dracula",
    label: "Dracula",
    isDark: true,
    vars: {
      "bg-base": "#282a36",
      "bg-panel": "#21222c",
      "bg-hover": "#343746",
      "bg-selected": "#44475a",
      border: "#4a4d63",
      "text-primary": "#f8f8f2",
      "text-secondary": "#d2d4e0",
      "text-muted": "#8b94bb",
      accent: "#bd93f9",
      "accent-dim": "#9a73d4",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      red: "#ff5555",
    },
    xterm: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#bd93f9",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
    shiki: "dracula",
  },
  // ── ported from crynta/terax-ai ──────────────────────────────────────────
  {
    key: "tokyo-night",
    label: "Tokyo Night",
    isDark: true,
    vars: {
      "bg-base": "#1a1b26",
      "bg-panel": "#1f2030",
      "bg-hover": "#292e42",
      "bg-selected": "#2a2d4a",
      border: "rgba(255,255,255,0.08)",
      "text-primary": "#c0caf5",
      "text-secondary": "#9aa5ce",
      "text-muted": "#6b7599",
      accent: "#7aa2f7",
      "accent-dim": "#5271c4",
      green: "#9ece6a",
      yellow: "#e0af68",
      red: "#f7768e",
    },
    xterm: {
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      cursorAccent: "#1a1b26",
      selectionBackground: "rgba(122,162,247,0.25)",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#ff7a93",
      brightGreen: "#b9f27c",
      brightYellow: "#ff9e64",
      brightBlue: "#7da6ff",
      brightMagenta: "#bb9af7",
      brightCyan: "#0db9d7",
      brightWhite: "#c0caf5",
    },
    shiki: "tokyo-night",
  },
  {
    key: "caffeine",
    label: "Caffeine",
    isDark: true,
    vars: {
      "bg-base": "#111111",
      "bg-panel": "#191919",
      "bg-hover": "#2a2a2a",
      "bg-selected": "#393028",
      border: "#201e18",
      "text-primary": "#eeeeee",
      "text-secondary": "#c4c4c4",
      "text-muted": "#b4b4b4",
      accent: "#ffe0c2",
      "accent-dim": "#cc9e80",
      green: "#b5c98f",
      yellow: "#ffd9a0",
      red: "#e06c75",
    },
    xterm: {
      background: "#111111",
      foreground: "#eeeeee",
      cursor: "#ffe0c2",
      cursorAccent: "#111111",
      selectionBackground: "rgba(255,224,194,0.20)",
      black: "#393028",
      red: "#e06c75",
      green: "#b5c98f",
      yellow: "#ffd9a0",
      blue: "#8fb0d9",
      magenta: "#cba6c9",
      cyan: "#88c0c8",
      white: "#d8cbb8",
      brightBlack: "#5c5046",
      brightRed: "#ff8a93",
      brightGreen: "#c9dba8",
      brightYellow: "#ffe6c4",
      brightBlue: "#a9c3e0",
      brightMagenta: "#ddc0db",
      brightCyan: "#a4d4da",
      brightWhite: "#f0e6d6",
    },
    shiki: "github-dark",
  },
  {
    key: "tide",
    label: "Tide",
    isDark: true,
    vars: {
      "bg-base": "#14191c",
      "bg-panel": "#1a2024",
      "bg-hover": "#232c30",
      "bg-selected": "#283330",
      border: "rgba(205,217,218,0.09)",
      "text-primary": "#cdd9da",
      "text-secondary": "#a8b8ba",
      "text-muted": "#93a3a4",
      accent: "#6cb6b0",
      "accent-dim": "#4a8f8a",
      green: "#8fc99a",
      yellow: "#d9bd80",
      red: "#e07a6a",
    },
    xterm: {
      background: "#14191c",
      foreground: "#cdd9da",
      cursor: "#6cb6b0",
      cursorAccent: "#14191c",
      selectionBackground: "rgba(108,182,176,0.20)",
      black: "#283330",
      red: "#e07a6a",
      green: "#8fc99a",
      yellow: "#d9bd80",
      blue: "#6fa8c9",
      magenta: "#c39bc4",
      cyan: "#6cb6b0",
      white: "#cdd9da",
      brightBlack: "#44504d",
      brightRed: "#ec8a7a",
      brightGreen: "#a0d6aa",
      brightYellow: "#e3c896",
      brightBlue: "#82bbd9",
      brightMagenta: "#d0aed0",
      brightCyan: "#82c8c2",
      brightWhite: "#e0eaeb",
    },
    shiki: "nord",
  },
  {
    key: "tide-light",
    label: "Tide Light",
    isDark: false,
    vars: {
      "bg-base": "#f2f6f5",
      "bg-panel": "#ffffff",
      "bg-hover": "#e3ecea",
      "bg-selected": "#dde7e4",
      border: "rgba(43,58,57,0.12)",
      "text-primary": "#2b3a39",
      "text-secondary": "#3d5352",
      "text-muted": "#5f6e6d",
      accent: "#2f7d76",
      "accent-dim": "#1f5f58",
      green: "#3a8a4f",
      yellow: "#a9802a",
      red: "#c0392b",
    },
    xterm: {
      background: "#f2f6f5",
      foreground: "#2b3a39",
      cursor: "#2f7d76",
      cursorAccent: "#f2f6f5",
      selectionBackground: "rgba(47,125,118,0.16)",
      black: "#2b3a39",
      red: "#c0392b",
      green: "#3a8a4f",
      yellow: "#a9802a",
      blue: "#3a6ea5",
      magenta: "#9a5a8a",
      cyan: "#2f7d76",
      white: "#c2c8c7",
      brightBlack: "#5a6968",
      brightRed: "#d04a3a",
      brightGreen: "#469a5f",
      brightYellow: "#b8902a",
      brightBlue: "#4a7eb5",
      brightMagenta: "#aa6a9a",
      brightCyan: "#3a958c",
      brightWhite: "#2b3a39",
    },
    shiki: "github-light",
  },
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: "stonks",
    label: "Stonks 🚀 (meme)",
    isDark: true,
    // Panel bgs are rgba with alpha so the meme wallpaper bleeds through every
    // surface. Accents are eye-melting neon — magenta/cyan/acid-green.
    vars: {
      "bg-base": "#0a0012",
      "bg-panel": "rgba(22, 0, 38, 0.62)",
      "bg-hover": "rgba(255, 32, 121, 0.18)",
      "bg-selected": "rgba(0, 240, 255, 0.22)",
      border: "#ff2079",
      "text-primary": "#f5e9ff",
      "text-secondary": "#c9a8ff",
      "text-muted": "#8a6bb0",
      accent: "#39ff14",
      "accent-dim": "#00f0ff",
      green: "#39ff14",
      yellow: "#ffe600",
      red: "#ff2079",
    },
    xterm: {
      // Transparent so the meme wallpaper shows under the terminal text.
      background: "rgba(10, 0, 18, 0.45)",
      foreground: "#f5e9ff",
      cursor: "#39ff14",
      cursorAccent: "#0a0012",
      selectionBackground: "#3a006a",
      black: "#1a0030",
      red: "#ff2079",
      green: "#39ff14",
      yellow: "#ffe600",
      blue: "#00f0ff",
      magenta: "#d400ff",
      cyan: "#00f0ff",
      white: "#f5e9ff",
      brightBlack: "#6b4a8f",
      brightRed: "#ff5c9d",
      brightGreen: "#7dff5c",
      brightYellow: "#fff04d",
      brightBlue: "#5cf0ff",
      brightMagenta: "#e85cff",
      brightCyan: "#5cf0ff",
      brightWhite: "#ffffff",
    },
    shiki: "synthwave-84",
    bgImage: STONKS_BG,
  },
  {
    key: "lime-void",
    label: "Lime Void 🟢",
    isDark: true,
    // Solid dark-lime theme. (A see-through "glass" variant relying on window
    // transparency + OS vibrancy was tried but caused system instability and
    // left surfaces unreadable, so it's fully opaque. Electric lime accent.)
    vars: {
      "bg-base": "#060a06",
      "bg-panel": "#0c140c",
      "bg-hover": "rgba(174, 255, 0, 0.14)",
      "bg-selected": "rgba(174, 255, 0, 0.22)",
      border: "rgba(174, 255, 0, 0.35)",
      "text-primary": "#eaffd6",
      "text-secondary": "#b6e89a",
      "text-muted": "#7fa86a",
      accent: "#aeff00",
      "accent-dim": "#7ab800",
      green: "#aeff00",
      yellow: "#eaff00",
      red: "#ff5470",
    },
    xterm: {
      background: "#060a06",
      foreground: "#eaffd6",
      cursor: "#aeff00",
      cursorAccent: "#060a06",
      selectionBackground: "rgba(174, 255, 0, 0.25)",
      black: "#0a0f0a",
      red: "#ff5470",
      green: "#aeff00",
      yellow: "#eaff00",
      blue: "#5cf0c8",
      magenta: "#c8ff5c",
      cyan: "#7affd6",
      white: "#eaffd6",
      brightBlack: "#5a6b4a",
      brightRed: "#ff7a90",
      brightGreen: "#c6ff4d",
      brightYellow: "#f4ff4d",
      brightBlue: "#7affd6",
      brightMagenta: "#d6ff7a",
      brightCyan: "#a6ffe6",
      brightWhite: "#ffffff",
    },
    shiki: "github-dark",
  },
  {
    key: "nebula",
    label: "Nebula",
    isDark: true,
    vars: {
      "bg-base": "#0d0e1f",
      "bg-panel": "#13152b",
      "bg-hover": "#1e2040",
      "bg-selected": "#2d2060",
      border: "#252745",
      "text-primary": "#e4e7f5",
      "text-secondary": "#8d96c0",
      "text-muted": "#5a6390",
      accent: "#7c5af5",
      "accent-dim": "#5a3dd0",
      green: "#22c55e",
      yellow: "#f59e0b",
      red: "#f0506e",
    },
    xterm: {
      background: "#0b0c1e",
      foreground: "#c0caf5",
      cursor: "#7c5af5",
      cursorAccent: "#0b0c1e",
      selectionBackground: "#2d2060",
      black: "#15162c",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
    shiki: "github-dark",
  },
  // ---------------------------------------------------------------------------
  // Counterpart variants. Every entry below exists so a THEME_FAMILY (see below)
  // can offer both a light and a dark side — they are not standalone designs,
  // they are the missing half of an existing theme.
  // ---------------------------------------------------------------------------
  {
    key: "ps-gray-dark",
    label: "Photoshop Gray Dark",
    isDark: true,
    // Photoshop CS6+ dark chrome: the same neutral grays, inverted.
    vars: {
      "bg-base": "#1e1e1e",
      "bg-panel": "#2b2b2b",
      "bg-hover": "#373737",
      "bg-selected": "#1f4f8f",
      border: "#3f3f3f",
      "text-primary": "#e8e8e8",
      "text-secondary": "#b4b4b4",
      "text-muted": "#828282",
      accent: "#4a90d9",
      "accent-dim": "#2f6fb3",
      green: "#5bb75b",
      yellow: "#d9a13a",
      red: "#d95c5c",
    },
    xterm: {
      background: "#1e1e1e",
      foreground: "#e8e8e8",
      cursor: "#4a90d9",
      cursorAccent: "#1e1e1e",
      selectionBackground: "#1f4f8f",
      black: "#2b2b2b",
      red: "#d95c5c",
      green: "#5bb75b",
      yellow: "#d9a13a",
      blue: "#4a90d9",
      magenta: "#a97bc4",
      cyan: "#4aacb8",
      white: "#c8c8c8",
      brightBlack: "#828282",
      brightRed: "#e87878",
      brightGreen: "#79c979",
      brightYellow: "#e8b657",
      brightBlue: "#6fa8e6",
      brightMagenta: "#c095d6",
      brightCyan: "#6bc3cd",
      brightWhite: "#f2f2f2",
    },
    shiki: "github-dark",
  },
  {
    key: "monokai-light",
    label: "Monokai Light",
    isDark: false,
    // Monokai's hues (pink/green/orange/violet) on the warm off-white paper the
    // Monokai Pro Light variants use.
    vars: {
      "bg-base": "#fdfcf6",
      "bg-panel": "#f5f3ea",
      "bg-hover": "#eae7da",
      "bg-selected": "#ded9c6",
      border: "#dcd7c6",
      "text-primary": "#2c2a25",
      "text-secondary": "#5b574c",
      "text-muted": "#8b8577",
      accent: "#d5187c",
      "accent-dim": "#a81161",
      green: "#5c9c14",
      yellow: "#b58900",
      red: "#d7301f",
    },
    xterm: {
      background: "#fdfcf6",
      foreground: "#2c2a25",
      cursor: "#d5187c",
      cursorAccent: "#fdfcf6",
      selectionBackground: "#ded9c6",
      black: "#2c2a25",
      red: "#d7301f",
      green: "#5c9c14",
      yellow: "#b58900",
      blue: "#2b7fbd",
      magenta: "#8c53c6",
      cyan: "#0f8f96",
      white: "#8b8577",
      brightBlack: "#6b6659",
      brightRed: "#ef4b39",
      brightGreen: "#74b52a",
      brightYellow: "#d3a017",
      brightBlue: "#4a9bd6",
      brightMagenta: "#a570dd",
      brightCyan: "#26a8af",
      brightWhite: "#1b1a16",
    },
    shiki: "github-light",
  },
  {
    key: "cobalt2-light",
    label: "Cobalt2 Light",
    isDark: false,
    // Cobalt2's signature orange/yellow on a pale blue-tinted paper.
    vars: {
      "bg-base": "#f7fbff",
      "bg-panel": "#e9f2fb",
      "bg-hover": "#dae8f6",
      "bg-selected": "#bcd9f2",
      border: "#c5daee",
      "text-primary": "#0b2b45",
      "text-secondary": "#345a7a",
      "text-muted": "#6b89a3",
      accent: "#e6841a",
      "accent-dim": "#b8620c",
      green: "#2f8f4e",
      yellow: "#c08b00",
      red: "#d33a2c",
    },
    xterm: {
      background: "#f7fbff",
      foreground: "#0b2b45",
      cursor: "#e6841a",
      cursorAccent: "#f7fbff",
      selectionBackground: "#bcd9f2",
      black: "#0b2b45",
      red: "#d33a2c",
      green: "#2f8f4e",
      yellow: "#c08b00",
      blue: "#1266b3",
      magenta: "#9a4bb8",
      cyan: "#0f8b9e",
      white: "#6b89a3",
      brightBlack: "#4c6c88",
      brightRed: "#e8574a",
      brightGreen: "#43a862",
      brightYellow: "#dda413",
      brightBlue: "#2f86d4",
      brightMagenta: "#b268cd",
      brightCyan: "#25a4b6",
      brightWhite: "#04203a",
    },
    shiki: "github-light",
  },
  {
    key: "solarized-dark",
    label: "Solarized Dark",
    isDark: true,
    // Ethan Schoonover's canonical base03 palette.
    vars: {
      "bg-base": "#002b36",
      "bg-panel": "#073642",
      "bg-hover": "#0c4855",
      "bg-selected": "#125666",
      border: "#0e4a58",
      "text-primary": "#eee8d5",
      "text-secondary": "#93a1a1",
      "text-muted": "#657b83",
      accent: "#268bd2",
      "accent-dim": "#1d6fa8",
      green: "#859900",
      yellow: "#b58900",
      red: "#dc322f",
    },
    xterm: {
      background: "#002b36",
      foreground: "#eee8d5",
      cursor: "#268bd2",
      cursorAccent: "#002b36",
      selectionBackground: "#125666",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#586e75",
      brightRed: "#cb4b16",
      brightGreen: "#93a1a1",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
    shiki: "solarized-dark",
  },
  {
    key: "alucard",
    label: "Alucard (Dracula Light)",
    isDark: false,
    // Dracula's official light counterpart: the same accents on warm cream.
    vars: {
      "bg-base": "#fffbeb",
      "bg-panel": "#f5f1de",
      "bg-hover": "#ebe6d0",
      "bg-selected": "#dcd7bf",
      border: "#e0dac2",
      "text-primary": "#1f1f1f",
      "text-secondary": "#4c4f5a",
      "text-muted": "#7b7f8b",
      accent: "#a34d9c",
      "accent-dim": "#7f3b7a",
      green: "#14710a",
      yellow: "#a3701a",
      red: "#cb3a2a",
    },
    xterm: {
      background: "#fffbeb",
      foreground: "#1f1f1f",
      cursor: "#a34d9c",
      cursorAccent: "#fffbeb",
      selectionBackground: "#dcd7bf",
      black: "#1f1f1f",
      red: "#cb3a2a",
      green: "#14710a",
      yellow: "#a3701a",
      blue: "#0552a8",
      magenta: "#a34d9c",
      cyan: "#036a96",
      white: "#7b7f8b",
      brightBlack: "#5c606b",
      brightRed: "#e05a48",
      brightGreen: "#2b8c1f",
      brightYellow: "#c08a2b",
      brightBlue: "#2a72c4",
      brightMagenta: "#bd68b6",
      brightCyan: "#1b87b3",
      brightWhite: "#0d0d0d",
    },
    shiki: "github-light",
  },
  {
    key: "tokyo-night-light",
    label: "Tokyo Night Light",
    isDark: false,
    // The upstream "Tokyo Night Light" variant: #d5d6db paper, #343b58 ink.
    vars: {
      "bg-base": "#e1e2e7",
      "bg-panel": "#d5d6db",
      "bg-hover": "#c8c9ce",
      "bg-selected": "#b7c1e3",
      border: "#c4c8da",
      "text-primary": "#343b58",
      "text-secondary": "#4c505e",
      "text-muted": "#787c99",
      accent: "#34548a",
      "accent-dim": "#2a4372",
      green: "#385f0d",
      yellow: "#8f5e15",
      red: "#8c4351",
    },
    xterm: {
      background: "#e1e2e7",
      foreground: "#343b58",
      cursor: "#34548a",
      cursorAccent: "#e1e2e7",
      selectionBackground: "#b7c1e3",
      black: "#343b58",
      red: "#8c4351",
      green: "#385f0d",
      yellow: "#8f5e15",
      blue: "#34548a",
      magenta: "#5a3e8e",
      cyan: "#0f4b6e",
      white: "#787c99",
      brightBlack: "#5a5f75",
      brightRed: "#a4535f",
      brightGreen: "#4d7a1d",
      brightYellow: "#ab7723",
      brightBlue: "#466aa8",
      brightMagenta: "#7256ab",
      brightCyan: "#1d6a91",
      brightWhite: "#252838",
    },
    shiki: "github-light",
  },
  {
    key: "caffeine-light",
    label: "Caffeine Light",
    isDark: false,
    // Latte, not espresso: the same roasted browns on steamed-milk paper.
    vars: {
      "bg-base": "#faf4ec",
      "bg-panel": "#f1e7d9",
      "bg-hover": "#e6d8c5",
      "bg-selected": "#dcc7ab",
      border: "#dfd0bb",
      "text-primary": "#33261a",
      "text-secondary": "#5e4a37",
      "text-muted": "#8b7460",
      accent: "#a2561d",
      "accent-dim": "#7d4114",
      green: "#5b7d16",
      yellow: "#a5791b",
      red: "#b2402b",
    },
    xterm: {
      background: "#faf4ec",
      foreground: "#33261a",
      cursor: "#a2561d",
      cursorAccent: "#faf4ec",
      selectionBackground: "#dcc7ab",
      black: "#33261a",
      red: "#b2402b",
      green: "#5b7d16",
      yellow: "#a5791b",
      blue: "#3d6a95",
      magenta: "#8a4c86",
      cyan: "#2c7f80",
      white: "#8b7460",
      brightBlack: "#6b5643",
      brightRed: "#c85a41",
      brightGreen: "#729a28",
      brightYellow: "#bf922f",
      brightBlue: "#5484ad",
      brightMagenta: "#a4649f",
      brightCyan: "#3f9899",
      brightWhite: "#241a11",
    },
    shiki: "github-light",
  },
  {
    key: "stonks-light",
    label: "Stonks ☀️ (meme)",
    isDark: false,
    // Same meme wallpaper, daylight edition: neon on paper. Still crazy.
    vars: {
      "bg-base": "#fff6fb",
      "bg-panel": "#ffe9f5",
      "bg-hover": "#ffd9ee",
      "bg-selected": "#ffc2e3",
      border: "#f6c8e2",
      "text-primary": "#2a0a1c",
      "text-secondary": "#6b2049",
      "text-muted": "#a1668a",
      accent: "#d1006b",
      "accent-dim": "#a30053",
      green: "#0f8f2a",
      yellow: "#b57c00",
      red: "#d81b2f",
    },
    xterm: {
      background: "#fff6fb",
      foreground: "#2a0a1c",
      cursor: "#d1006b",
      cursorAccent: "#fff6fb",
      selectionBackground: "#ffc2e3",
      black: "#2a0a1c",
      red: "#d81b2f",
      green: "#0f8f2a",
      yellow: "#b57c00",
      blue: "#0f6fd1",
      magenta: "#d1006b",
      cyan: "#0090a8",
      white: "#a1668a",
      brightBlack: "#7c3f63",
      brightRed: "#f0405a",
      brightGreen: "#2eab48",
      brightYellow: "#d29a16",
      brightBlue: "#3a8ee0",
      brightMagenta: "#ec2f8f",
      brightCyan: "#16adc4",
      brightWhite: "#1b0512",
    },
    shiki: "github-light",
    bgImage: STONKS_LIGHT_BG,
  },
  {
    key: "lime-glow",
    label: "Lime Glow 🟢",
    isDark: false,
    // The lime accent kept, the void swapped for daylight.
    vars: {
      "bg-base": "#f7fdf4",
      "bg-panel": "#ecf8e6",
      "bg-hover": "#ddf0d3",
      "bg-selected": "#c7e6b7",
      border: "#d3e9c8",
      "text-primary": "#12240c",
      "text-secondary": "#3a5230",
      "text-muted": "#6d855f",
      accent: "#3f8f0c",
      "accent-dim": "#2f6d09",
      green: "#2f8f2a",
      yellow: "#9c8309",
      red: "#c0392b",
    },
    xterm: {
      background: "#f7fdf4",
      foreground: "#12240c",
      cursor: "#3f8f0c",
      cursorAccent: "#f7fdf4",
      selectionBackground: "#c7e6b7",
      black: "#12240c",
      red: "#c0392b",
      green: "#2f8f2a",
      yellow: "#9c8309",
      blue: "#2e6fa8",
      magenta: "#8a4a9c",
      cyan: "#1f8285",
      white: "#6d855f",
      brightBlack: "#4d6541",
      brightRed: "#d8503f",
      brightGreen: "#46a83f",
      brightYellow: "#b89b1c",
      brightBlue: "#4587c0",
      brightMagenta: "#a463b5",
      brightCyan: "#33999c",
      brightWhite: "#091905",
    },
    shiki: "github-light",
  },
  {
    key: "nebula-light",
    label: "Nebula Light",
    isDark: false,
    // Daytime nebula: the violet/cyan accents over a cool lilac-white sky.
    vars: {
      "bg-base": "#faf8ff",
      "bg-panel": "#f0ecfb",
      "bg-hover": "#e4ddf6",
      "bg-selected": "#d2c6ef",
      border: "#ded6f2",
      "text-primary": "#1b1630",
      "text-secondary": "#463c68",
      "text-muted": "#776d95",
      accent: "#6d3ecb",
      "accent-dim": "#5229a5",
      green: "#0f8a63",
      yellow: "#a37a10",
      red: "#cb3355",
    },
    xterm: {
      background: "#faf8ff",
      foreground: "#1b1630",
      cursor: "#6d3ecb",
      cursorAccent: "#faf8ff",
      selectionBackground: "#d2c6ef",
      black: "#1b1630",
      red: "#cb3355",
      green: "#0f8a63",
      yellow: "#a37a10",
      blue: "#3a5ecb",
      magenta: "#6d3ecb",
      cyan: "#10829b",
      white: "#776d95",
      brightBlack: "#564c78",
      brightRed: "#e14e6e",
      brightGreen: "#28a37c",
      brightYellow: "#bf9524",
      brightBlue: "#5878e0",
      brightMagenta: "#8a5ee0",
      brightCyan: "#26a0ba",
      brightWhite: "#100c20",
    },
    shiki: "github-light",
  },
];

export const DEFAULT_THEME_KEY = "dark";

export function findTheme(key: string): Theme {
  return THEMES.find((t) => t.key === key) ?? THEMES[0];
}

// A theme FAMILY is a light/dark pair of the variants above — what the user
// picks in Settings. The app never applies a family directly: the color-scheme
// mode (system/light/dark) chooses which half of the pair is live, so one pick
// covers both schemes and switching mode never lands on an unrelated theme.
export interface ThemeFamily {
  key: string;
  label: string;
  light: string; // variant key applied when the scheme resolves to light
  dark: string; //  variant key applied when the scheme resolves to dark
}

export const THEME_FAMILIES: ThemeFamily[] = [
  { key: "burrow", label: "Burrow", light: "light", dark: "dark" },
  { key: "ps-gray", label: "Photoshop Gray", light: "ps-gray", dark: "ps-gray-dark" },
  { key: "monokai", label: "Monokai", light: "monokai-light", dark: "monokai" },
  { key: "cobalt2", label: "Cobalt2", light: "cobalt2-light", dark: "cobalt2" },
  { key: "solarized", label: "Solarized", light: "solarized-light", dark: "solarized-dark" },
  { key: "dracula", label: "Dracula", light: "alucard", dark: "dracula" },
  { key: "tokyo-night", label: "Tokyo Night", light: "tokyo-night-light", dark: "tokyo-night" },
  { key: "caffeine", label: "Caffeine", light: "caffeine-light", dark: "caffeine" },
  { key: "tide", label: "Tide", light: "tide-light", dark: "tide" },
  { key: "nebula", label: "Nebula", light: "nebula-light", dark: "nebula" },
  { key: "lime-void", label: "Lime Void 🟢", light: "lime-glow", dark: "lime-void" },
  { key: "stonks", label: "Stonks 🚀 (meme)", light: "stonks-light", dark: "stonks" },
];

export const DEFAULT_FAMILY_KEY = "burrow";

export function findFamily(key: string): ThemeFamily {
  return THEME_FAMILIES.find((f) => f.key === key) ?? THEME_FAMILIES[0];
}

// Which family a variant key belongs to — used to highlight the right card and
// to migrate installs that stored a bare variant key as their theme pick.
export function familyOf(variantKey: string): ThemeFamily {
  return (
    THEME_FAMILIES.find((f) => f.light === variantKey || f.dark === variantKey) ??
    THEME_FAMILIES[0]
  );
}

// The variant of `family` for a resolved scheme.
export function variantFor(family: ThemeFamily, scheme: "light" | "dark"): Theme {
  return findTheme(scheme === "dark" ? family.dark : family.light);
}
